config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games, only: [:index] do
    collection do
      get :destroy_all
      get :update_all
    end
  end

  resources :teams, only: [:index] do
    collection do
      get :destroy_all
      get :update_all
    end
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do
    resources :games, only: [:index]
    resources :teams, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :league
  belongs_to :home_team, class_name: "Team", foreign_key: "home_team_id"
  belongs_to :away_team, class_name: "Team", foreign_key: "away_team_id"
end

app/models/league.rb
class League < ApplicationRecord
  has_many :games
  has_many :teams
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :league
  has_many :games
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
end

app/controllers/api_v1/games_controller.rb
class ApiV1::GamesController < ApplicationController
  def index
    games = Game.all
    render :json => games.to_json
  end
end

app/controllers/api_v1/teams_controller.rb
class ApiV1::TeamsController < ApplicationController
  def index
    teams = Team.all
    render :json => teams.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  require "scraper_helper.rb"
  require "scraper/mlb_games.rb"

  def index
    @games = Game.includes(:home_team, :away_team)
  end

  def destroy_all
    Game.destroy_all

    redirect_to games_path
  end

  def update_all
    ScraperHelper::MlbGames.run
    redirect_to games_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  require "scraper_json_helper.rb"
  require "scraper_json/mlb_teams.rb"

  def index
    @teams = Team.all
  end

  def destroy_all
    Team.destroy_all
    redirect_to teams_path
  end

  def update_all
    ScraperJsonHelper::MlbTeams.run
    redirect_to teams_path
  end
end

app/helpers/api_v1/games_helper.rb
module ApiV1::GamesHelper
end

app/helpers/api_v1/teams_helper.rb
module ApiV1::TeamsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def league_name(league_id)
    case league_id
    when 2
      "MLB"
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def games_status(status_number)
    case status_number
    when 0
      "未開打"
    when 1
      "進行中"
    when 2
      "結束"
    when 3
      "延賽"
    end
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<%=form_tag games_path,class: "form-horizontal",method: :get, role:"form" do%>
  <div class="form-group">
    <%=label_tag :test,"Test",class: "col-xs-1 control-label" %>
    <div class="col-xs-2">
      <%=submit_tag "Test", class: "btn btn-info"%>
    </div>
  </div>
<%end%>
<%= link_to 'Games Scraper', update_all_games_path, class: "btn btn-info"%>
<%= link_to 'Games Destroy', destroy_all_games_path, class: "btn btn-danger"%>
<%= link_to 'Games API', v1_games_path, target: :_blank , class: "btn btn-primary"%>
<%= link_to 'Source', 'https://www.si.com/mlb/scoreboard?date=2018-07-10', target: :_blank , class: "btn btn-warning"%>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Official id</th>
      <th>League</th>
      <th>Game Time</th>
      <th>Home Team</th>
      <th>Away Team</th>
      <th>Home Team Score</th>
      <th>Away Team Score</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <%@games.each do |game|%>
    <tr>
      <td><%= game.official_id%></td>
      <td><%= league_name(game.league_id) %></td>
      <td><%= game.game_time%></td>
      <td><%= game.home_team.try(:name)%></td>
      <td><%= game.away_team.try(:name)%></td>
      <td><%= game.home_team_score%></td>
      <td><%= game.away_team_score%></td>
      <td><%= games_status(game.status)%></td>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Games', games_path%></li>
<li><%= link_to 'Teams', teams_path%></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataSport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= yield %>
    </main>
  </body>
</html>